// Central list of screen names used in App.currentScreen to avoid typos and keep navigation consistent.
export const SCREENS = {
  Splash: "Splash",
  SignIn: "SignIn",
  SignUp: "SignUp",
  SignUpLocation: "SignUpLocation",
  OTPVerification: "OTPVerification",
  RecoveryPhrase: "RecoveryPhrase",
  RecoveryPhraseVerification: "RecoveryPhraseVerification",
  RegistrationSplash: "RegistrationSplash",
  CreatePin: "CreatePin",
  CreateSavingsPrompt: "CreateSavingsPrompt",
  CreateSavingsBio: "CreateSavingsBio",
  CreateSavingsDetails: "CreateSavingsDetails",
  SavingsProcessing: "SavingsProcessing",
  AppLaunchPin: "AppLaunchPin",
  Main: "Main",

  Home: "Home",
  Profile: "Profile",
  Savings: "Savings",

  Deposit: "Deposit",
  Withdraw: "Withdraw",
  ConfirmPayment: "ConfirmPayment",
  PaymentProcessing: "PaymentProcessing",
  TransactionResult: "TransactionResult",
  TransactionReceipt: "TransactionReceipt",
  TransactionHistory: "TransactionHistory",
  DownloadStatement: "DownloadStatement",
  SavingsDetail: "SavingsDetail",

  Notifications: "Notifications",
  SecurityPrivacy: "SecurityPrivacy",
  PersonalInfo: "PersonalInfo",
  PrivacyPolicy: "PrivacyPolicy",
  SavedCards: "SavedCards",
  SavedAccounts: "SavedAccounts",

  AddPaymentSource: "AddPaymentSource",
  CardVerification: "CardVerification",
  SaveCardDetails: "SaveCardDetails",
  CardPaymentMethod: "CardPaymentMethod",
  CardPaymentOTP: "CardPaymentOTP",
  CardPaymentProcessing: "CardPaymentProcessing",
  BankTransferPayment: "BankTransferPayment",
  BankTransferInstructions: "BankTransferInstructions",

  AddBankAccount: "AddBankAccount",
  BankAccountVerification: "BankAccountVerification",
  LinkCardSuccess: "LinkCardSuccess",
  LockSavingsMethod: "LockSavingsMethod",
  ResetPIN: "ResetPIN",
  CloseAccount: "CloseAccount",

  ForgotPassword: "ForgotPassword",
  ForgotTransactionPin: "ForgotTransactionPin",
  CreateNewPassword: "CreateNewPassword",
  PasswordResetSuccess: "PasswordResetSuccess",
  ResetPassword: "ResetPassword",

  ForgotAppLaunchPin: "ForgotAppLaunchPin",

  // email verification flow
  EmailSent: "EmailSent",
  VerifyAccount: "VerifyAccount",
  VerifyAccountProcessing: "VerifyAccountProcessing",
  AccountCreationProcessing: "AccountCreationProcessing",
  AccountCreatedSuccess: "AccountCreatedSuccess",
  // ... add new screen names as needed
};
